using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace rebuy___buy_used_products__community_
{
    /// <summary>
    /// Interaction logic for camera.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class camera : ContentPage
    {
        public camera()
        {
            InitializeComponent();
        }
    }
}
	