using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace rebuy___buy_used_products__community_
{
    /// <summary>
    /// Interaction logic for product_details.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class product_details : ContentPage
    {
        public product_details()
        {
            InitializeComponent();
        }
    }
}
	