using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace rebuy___buy_used_products__community_
{
    /// <summary>
    /// Interaction logic for side_bar.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class side_bar : ContentPage
    {
        public side_bar()
        {
            InitializeComponent();
        }
    }
}
	